Dodanie spawnowania przeciwników co stage
Lyulf/PIO_3-Just-Another-Rougelike pull request #24
Opened 2023-06-14 21:45 UTC by thejerremi

2023-06-14 22:14 UTC, Lyulf requested changes

2023-06-14 22:14 UTC, Lyulf commented on client.py
> +        # self.engine.spawn_opponents(1)
Można chyba już na stałe usunąć

2023-06-14 22:14 UTC, Lyulf commented on systems/enemy_spawn_system.py
> +            self.max_enemies_at_once = self.max_enemies_on_stage
Nie jestem pewien po co są te linijki

2023-06-14 22:14 UTC, Lyulf commented on systems/enemy_spawn_system.py
> +        enemiesAlive = 0
Trzeba zmienić na SnakeCase: enemies_alive

2023-06-14 22:14 UTC, Lyulf commented on systems/enemy_spawn_system.py
> +                self.spawned_enemies += 1
Można rozdzielić te if'y, żeby były bardziej przejrzyste:
```python
if enemies_alive:
    return;
# itd
```
Dodatkowo, zamieniłbym by przeciwnicy randomowo wybierali kierunki i dałbym żeby mogli też wyjść od góry:
```python
#przykład
import random
from enum import Enum

class Direction(Enum):
    LEFT = 0
    RIGHT = 1
    UP = 2

direction = random.choice(list(Direction))
if direction == Direction.LEFT:
    # spawn on left
elif direction == Direction.RIGHT:
    # spawn on right
elif direction == Direction.UP:
    # spawn up
self.spawned_enemies += 1
```
Spawnowanie sam z kodu możesz przerzucić.

2023-06-14 22:33 UTC, thejerremi commented on systems/enemy_spawn_system.py
> +        pass
Usunięte

2023-06-14 22:33 UTC, thejerremi commented on systems/enemy_spawn_system.py
> +        self.spawned_enemies = 0
Przeniesione oraz usunięty init

2023-06-14 22:34 UTC, thejerremi commented on engine/game_engine.py
> +        self.add_system(8, EnemySpawnSystem)
Wrzuciłem przed `GameStateSystem` bo ten system korzysta z niego.

2023-06-14 22:34 UTC, thejerremi commented on client.py
> +        # self.engine.spawn_opponents(1)
Usunięte

2023-06-14 22:36 UTC, thejerremi commented on systems/enemy_spawn_system.py
> +            self.max_enemies_at_once = self.max_enemies_on_stage
Wcześniej przy tworzeniu były potrzebne, teraz rzeczywiście są do usunięcia.

2023-06-14 22:36 UTC, thejerremi commented on systems/enemy_spawn_system.py
> +        enemiesAlive = 0
Zrefactorowane

2023-06-14 22:43 UTC, thejerremi commented on systems/enemy_spawn_system.py
> +                self.spawned_enemies += 1
> Dodatkowo, zamieniłbym by przeciwnicy randomowo wybierali kierunki i dałbym żeby mogli też wyjść od góry:

Zrobione

2023-06-14 22:50 UTC, Lyulf commented on engine/game_engine.py
> +        self.add_system(8, EnemySpawnSystem)
Jest po GameStateSystem'ie, ale zakładam, że to miałeś na myśli tak?

2023-06-14 22:51 UTC, Lyulf commented on systems/enemy_spawn_system.py
> +            self.max_enemies_at_once = self.max_enemies_on_stage
Nadal te linijki są

2023-06-14 22:58 UTC, Lyulf commented on systems/enemy_spawn_system.py
> +                self.spawned_enemies += 1
Nadal bym rozdzielił tego if'a i dałbym by state == FIGHTING był w elif'ie, a nie if'ie. Na szybko dałem tak rozdzieliłem:
```python
        if self.spawned_enemies == self.max_enemies_on_stage and enemies_alive == 0:
            self.game_state_system.state = GameStates.GO_NEXT_AREA
        elif self.game_state_system.state == GameStates.FIGHTING:
            if enemies_alive != self.max_enemies_at_once and self.spawned_enemies < self.max_enemies_on_stage:
                spawn_direction = random.choice(list(SpawnDirection))
                if spawn_direction == SpawnDirection.LEFT:
                    self.prefab_manager.spawn('demon', pygame.Vector2(-1, 380))
                elif spawn_direction == SpawnDirection.RIGHT:
                    self.prefab_manager.spawn('demon', pygame.Vector2(961, 380))
                elif spawn_direction == SpawnDirection.UP:
                    self.prefab_manager.spawn('demon', pygame.Vector2(520, -1))
                self.spawned_enemies += 1
```

2023-06-15 12:34 UTC, thejerremi commented on engine/game_engine.py
> +        self.add_system(8, EnemySpawnSystem)
Tak, po gamestate chciałem

2023-06-15 12:34 UTC, thejerremi commented on systems/enemy_spawn_system.py
> +            self.max_enemies_at_once = self.max_enemies_on_stage
Teraz na pewno usunięte

2023-06-15 12:39 UTC, Lyulf approved these changes

2023-06-15 12:40 UTC, merged